---
title: CivicTechSweden
timezone: Europe/Stockholm
baseurl: ''
collections:
  events:
    title: Events
    output: true
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  groups:
    title: Groups
    output: true
    permalink: "/:title/"
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: form
    type: pages
  values:
    layout: event
    lang: sv
- scope:
    path: en/form
    type: pages
  values:
    layout: event
    lang: en
- scope:
    path: ''
    type: groups
  values:
    layout: page
    lang: sv
- scope:
    path: ''
    type: posts
  values:
    is_post: true
    layout: page
    lang: sv
    ref:
    excerpt:
    ingress-text:
    image:
    links:
    - title:
      url:
    contact:
    - name:
      image:
      text:
      mail:
      organisation:
      organisation-link:
- scope:
    path: ''
    type: events
  values:
    layout: event
    lang: sv
    ref:
    group:
    image:
    excerpt:
    ingress-text:
    event-date:
    event-date-desc:
    place:
    links:
    - title:
      url:
      style:
permalink: "/projects/:title/"
description: Hackathons för Sveriges Civic Tech-community
theme: jekyll-theme-cayman
plugins:
- jemoji
t:
  sv:
    event-title: Event
    more-events: Fler event
    project-title: Projekt
    project-chat: Chatta om projektet
    more-projects: Fler projekt
    project-events: Deltar i
    participating-projects: Deltagande projekt
    partner-title: Partners
    participating-partners: Deltagande grupper
    local-partners: Lokala partners
    start-group: Starta i din stad!
    start-group-url: "/about/#starta-en-grupp"
    mission: CivicTech Sweden är ett nätverk av personer, organisationer och offentliga aktörer som verkar för att möjligheterna med öppen och fri digitalisering ska komma så många som möjligt till del.
    language: Svenska
  en:
    event-title: Events
    more-events: More events
    project-title: Projects
    project-chat: Chat about the project
    more-projects: More projects
    project-events: Participating in
    participating-projects: Participating projects
    partner-title: Partners
    participating-partners: Participating groups
    local-partners: Local partners
    start-group: Start a group!
    start-group-url: "/en/about/#start-a-group"
    mission: CivicTechSweden is a network of individuals, organisations and the public sector working to make the possibilities that comes with digital technology benefit as many as possible.
    language: English
